services:
  - type: web
    name: healthcare-tracker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: TBosFbSoMsULYBxgQTcFEUqsezpBgrEy
    dockerContext: ./healthcare
    dockerfilePath: ./healthcare/Dockerfile